site_name: ORDA
theme:
  language: ru
  name: material
  
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
    

  features:
    - search.highlight
    - search.share
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.footnote.tooltips
    - navigation.icons
    - navigation.path
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - navigation.indexes
    - toggles
    
  icons:
     - fontawesome: true

  highlightjs: true
  hljs_languages:
    - yaml
    - rust
    - python
    - go
    - js
    - c++
    - C#

markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - footnotes
  - attr_list
  - md_in_html
  - tables

nav:
  - Blog:
    - blog/index.md
  - Безопасность приложений: 
    - 'Web Security': 'web_sec.md'
    - 'Mobile Secuirty': 'mob_sec.md'
    - 'Desktop Security': 'des_sec.md'
  - Инструменты DevSecOps: 'DevSecOps.md'
  - Стандарты безопасной разработки: 'standards.md'
  - Фреймворки безопасной разработки: 'frameworks.md'
  - Методология: 'methodology.md'
  - Обучение:
    - 'Курсы': 'Courses.md'
    - 'Лабораторные работы': 'Labs.md'
    - 'CTF': 'CTF.md'
  - Я - разработчик: 
    - 'Полезные материалы для разработчиков': 'dev_material.md'
  - Вакансии: 
    - 'Я ищу работу': 'job_search.md'
    - 'Я нанимаю': 'job_hunt.md'
  - Как стать контрибутором: 'HowTOBEContrib.md'



extra:
  consent:
    title: Куки кику
    description: >- 
      Мы используем твои печеньки .. Впрочем, ты и так всё понимаешь.
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/cyberorda
      name: telegram сообщество для ORDA
  generator: false
  

  analytics: 
    feedback:
      title: Была ли полезной эта страница
      ratings:
        - icon: material/emoticon-happy-outline
          name: Эта страница помогла мне
          data: 1
          note: >-
            Спасибо за отзыв!
        - icon: material/emoticon-sad-outline
          name: Эту страницу можно улучшить
          data: 0
          note: >- 
            Пожалуйста, создайте Issue на <a href="https://github.com/CyberOrda/cyberorda.github.io/issues" target="_blank" rel="noopener">гитхабе</a> этого проекта.


plugins:
  - privacy:
      cache: false
      enabled: !ENV [CI, false]
  - blog:
      post_date_format: medium
      archive_date_format: yyyy
      categories: true
      categories_name: DevSecOps
      post_dir: "{blog}/posts"
  - tags:
  - search:
      lang: 
        - ru
        - en
  - git-committers:
      repository: CyberOrda/cyberorda.github.io
      branch: main
      enabled: !ENV [CI, false]
  
  - git-revision-date-localized:
      enable_creation_date: true
      enabled: !ENV [CI, false]
      type: date

  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
      cache_safe: true


repo_url: https://github.com/CyberOrda/cyberorda.github.io
repo_name: CyberOrda/cyberorda.github.io

extra_css:
  - stylesheets/extra.css
   

extra_javascript:
  - javascripts/consent.js
  - javascripts/feedback.js
  - javascripts/shortcuts.js

copyright: >
  Copyright &copy; 2024 ORDA –
  <a href="#__consent">Настроить cookie</a>